name: rats
favicon: null
layout_spectrum: 0.00091
typography_spectrum: 0.62204
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1d1cf'
    - '#b1b3b2'
    - '#211d1e'
    - '#554c4d'
    - '#75746f'
  brandStrength: 0.0625
  lightness: 0.375
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
