name: rats
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/06b2ca91-7194-42dd-b1d4-ec96557cef85.jpg
layout_spectrum: 0.173142
typography_spectrum: 0.62204
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#FFFFFF'
    - '#B2B2B2'
    - '#1F2326'
    - '#E0E2EE'
    - '#404558'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.694257
purpose: []
title: ''
author:
  name: 'Richard Tomaino '
  url: ''
  email: alfiotomaino@gmail.com
content_rating:
  adult: false
