analytics: {}
color:
  brandColors:
    - '#FFFFFF'
    - '#B2B2B2'
    - '#1F2326'
    - '#E0E2EE'
    - '#404558'
  brandStrength: 0.25
  lightness: 0.375
  rhythmicContrast: 0.694257
  saturation: 0.3125
cta: {}
layout_spectrum: 0.173142
name: rats
opengraph: {}
purpose: []
typography_spectrum: 0.62204
