typography_spectrum: 0.5159284682013094
content_rating:
  adult: false
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.4312195316888392
  lightness: 0.9276446094736457
  saturation: 0.5187114828731865
  rhythmicContrast: 0.5473931340966374
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.20249786647036672
analytics: {}
author:
  name: 'Richard Tomaino '
  url: ''
  email: alfiotomaino@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c6db5bac-2147-4ccd-93e0-773960c1ec09.jpg
name: 'Richard Tomaino Sculpture '
cta: {}
favicon: null
title: RTS
coverPrefs:
  filter: false
description: A Melbourne based sculptor...
purpose: []
