layout_spectrum: 0.11834677751176059
typography_spectrum: 0.5159284682013094
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.7940865606069565
  lightness: 0.34258296876214445
  saturation: 0.847036951687187
  rhythmicContrast: 0.056672695791348815
coverPrefs:
  filter: false
name: 'Richard Tomaino Sculpture '
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c6db5bac-2147-4ccd-93e0-773960c1ec09.jpg
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
purpose: []
title: >-
  A Melbourne based sculptor, exploring silicon, stoneware and porcelain
  mediums. For private enquiries please contact alfiotomaino@gmail.com 
author:
  name: 'Richard Tomaino '
  url: ''
  email: alfiotomaino@gmail.com
content_rating:
  adult: false
