name: rats
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7214
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1d1cf'
    - '#b1b3b2'
    - '#211d1e'
    - '#554c4d'
    - '#75746f'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
