name: 'Richard Tomaino Sculpture '
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/06b2ca91-7194-42dd-b1d4-ec96557cef85.jpg
layout_spectrum: 0.5304184819106013
typography_spectrum: 0.5159284682013094
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#FFFFFF'
    - '#B2B2B2'
    - '#1F2326'
    - '#E0E2EE'
    - '#404558'
  brandStrength: 0.3131869905628264
  lightness: 0.9011426491197199
  saturation: 0.609807415632531
  rhythmicContrast: 0.9824206712655723
purpose: []
title: >-
  I am a Melbourne based ceramic and automotive sculptor. Utilizing both
  silicon, stoneware and porcelain mediums to define a unique contemporary
  aesthetic. For private enquiries please contact
  richardtomainosculpture@gmail.com   
author:
  name: 'Richard Tomaino '
  url: ''
  email: alfiotomaino@gmail.com
content_rating:
  adult: false
